<a href="https://colab.research.google.com/github/OrthrusB/ML-From-Scratch/blob/main/Introduction/BasicMaths.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basic Maths
-  matrix
- vector

#vector



euclidean distance

In [1]:
# calculate the eculidian distance between two list
list1 = [1,2,3]
list2 = [4,5,6]

x = sum((b-a)**2 for a,b in zip(list1,list2))**0.5
print("euclidian distance between two list is: ",x)

euclidian distance between two list is:  5.196152422706632


In [2]:
import numpy as np

In [3]:
#calculate the euclidina distane between vector using the numpy array
p1 = np.array([1,2,3])
p2 = np.array([4,5,6])


x = np.linalg.norm(p2-p1)
print("euclidian distance between two list is: ",x)

euclidian distance between two list is:  5.196152422706632


In [4]:
# calculate the euclidina distance between vector with out linalg
import numpy as np
a = np.array((1, 2, 3))
b = np.array((4, 5, 6))
dist = np.sqrt((b[0] - a[0])**2 + (b[1] - a[1])**2 + (b[2] - a[2])**2)
print(dist)
#dist = np.sqrt(np.sum((b - a) ** 2))

5.196152422706632


Manhattan Distance

In [5]:
#calculate the manhattan distane between vector using the numpy array
p1 = np.array([1,2,3])
p2 = np.array([4,5,6])


x = np.linalg.norm(p2-p1,ord=1)
print("manhattan distance between two list is: ",x)

manhattan distance between two list is:  9.0


In [6]:
#calculate the manhattan distane between vector using the numpy array
p1 = np.array([1,2,3])
p2 = np.array([4,5,6])


x = np.sum(abs(p2-p1))
print("manhattan distance between two list is: ",x)


manhattan distance between two list is:  9


In [7]:
#lenght or magnitude
#formula is sqrt xa**2 + x2**2

p1 = np.array([1,2,3,4])

#calcualte the magnitude of p1 |p1|
x = np.linalg.norm(p1)
print(x)

5.477225575051661


In [8]:
#lenght or magnitude
#formula is sqrt xa**2 + x2**2

p1 = np.array([1,2,3,4])

#calcualte the magnitude of p1 |p1|
x = np.sqrt(np.sum(p1**2))
print(x)

5.477225575051661


In [ ]:
#dot product
p1 = np.array([1,2,3])
p2 = np.array([4,5,6])

x = np.dot(p1,p2)
print(x)

# Matrix

In [9]:
#addition and subtraction of matrix
p1 = np.array([(1,2,3),(6,7,8)])
p2 = np.array([(4,5,6),(2,3,4)])

#add
sum = p1 + p2
print(sum)

#sub
sub = p1 - p2
print(sub)

[[ 5  7  9]
 [ 8 10 12]]
[[-3 -3 -3]
 [ 4  4  4]]


In [10]:
#dot product , second matrix should have the same no of rows as the same no of columns first matrix
p1 = np.array([(1,2,3),(6,7,8)])
p2 = np.array([(4,5,6),(2,3,4),(4,8,1)])

dot_p = np.dot(p1,p2)
print(dot_p)

[[ 20  35  17]
 [ 70 115  72]]


In [11]:
# determinant of matrix
p1 = np.array([(3,2),(6,7)])

det = np.linalg.det(p1)
print(det)


8.999999999999998


In [12]:
# inverse of the matrix
inv = np.linalg.inv(p1)
print(inv)

[[ 0.77777778 -0.22222222]
 [-0.66666667  0.33333333]]


In [13]:
#transpose of matrix
tran = p1.T
print(tran)

[[3 6]
 [2 7]]


In [ ]:
#input the matrix col and their values and do some operation
matrixA = []
matrixB = []
rows1 = int(input("Enter the no of rows of matrix A: "))
cols1 = int(input("Enter the no of cols of matrix A: "))

#get input for matrix 1
for i in range(rows1):
  r=[]
  for j in range(cols1):
    v = int(input(f"Enter the values for matrix A: "))
    r.append(v)
  matrixA.append(r)


rows2 = int(input("\nEnter the no of rows of matrix B: "))
cols2 = int(input("Enter the no of cols of matrix B: "))

#get input fro matrix 2
for i in range(rows2):
  r=[]
  for j in range(cols2):
    v = int(input(f"Enter the values for matrix B: "))
    r.append(v)

  matrixB.append(r)

matrixA = np.asarray(matrixA)
matrixB = np.asarray(matrixB)

print("\nmatrix A:\n",matrixA)
print("\nmatrix B:\n",matrixB,"\n")


#function to perform addition
def sum():
  print("\nThe addition of two matrix is:\n",matrixA + matrixB,"\n")

#function to perform subtraction
def sub():
  print("\nThe subtraction of two matrix is:\n",matrixA - matrixB,"\n")

#function to perform multiplication
def mul():
  print("\nThe multiplication of two matrix is:\n",np.multiply(matrixA,matrixB),"\n")

#function to perform dotproduct
def dot():
  print("\nThe dot product of two matrix is:\n",np.dot(matrixA,matrixB),"\n")




while True:
  print("\n-----Select the operation to perform-----\n")
  print("1.Addition")
  print("2.Subtraction")
  print("3.Multiplication")
  print("4.Dot product")
  print("5.Exit\n")

  num = int(input(("Enter the your choice:")))

  if num == 1:
    if(rows1 != rows2 or cols1 != cols2):
      print("\nCannot perform addition as it has different dimensions")
      continue
    else:
      sum()
  elif num == 2:
    if(rows1 != rows2 or cols1 != cols2):
      print("\nCannot perform subtraction as it has different dimensions")
      continue
    else:
      sub()
  elif num == 3:
    if(cols1 != rows2 or cols1 != cols2):
      print("\nCannot perform mulitplication Columns of A must be equal to rows of B.")
      continue
    else:
      mul()
  elif num == 4:
    if(cols1 != rows2):
      print("\nCannot perform mulitplication Columns of A must be equal to rows of B.")
      continue
    else:
      dot()
  elif num == 5:
    print("\n----Terminated----\n")
    break
  else:
    print("valid number")
    continue






Enter the no of rows of matrix A: 2
Enter the no of cols of matrix A: 3
Enter the values for matrix A: 5
Enter the values for matrix A: 6
Enter the values for matrix A: 8
Enter the values for matrix A: 3
Enter the values for matrix A: 1
Enter the values for matrix A: 3

Enter the no of rows of matrix B: 2
Enter the no of cols of matrix B: 3
Enter the values for matrix B: 7
Enter the values for matrix B: 5
Enter the values for matrix B: 9
Enter the values for matrix B: 5
Enter the values for matrix B: 3
Enter the values for matrix B: 2

matrix A:
 [[5 6 8]
 [3 1 3]]

matrix B:
 [[7 5 9]
 [5 3 2]] 


-----Select the operation to perform-----

1.Addition
2.Subtraction
3.Multiplication
4.Dot product
5.Exit

Enter the your choice:1

The addition of two matrix is:
 [[12 11 17]
 [ 8  4  5]] 


-----Select the operation to perform-----

1.Addition
2.Subtraction
3.Multiplication
4.Dot product
5.Exit

Enter the your choice:2

The subtraction of two matrix is:
 [[-2  1 -1]
 [-2 -2  1]] 


-----Se