<a href="https://colab.research.google.com/github/OrthrusB/ML-From-Scratch/blob/main/Introduction/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Introduction to NumPy

##what we will conver?
- creating arrays
- multidimensional array
- randomly generated arrays
- element wise operations
- summarizing operations

# One dimesnional array

In [1]:
import numpy as np
#create and array with all the element zeros

In [2]:
#element with ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [3]:
#create an array of size 10 with all elements 3
np.full(10, 3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [4]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [5]:
arr=np.array([5, 6, 7, 8, 9])
arr[3]=10
print(arr)

[ 5  6  7 10  9]


In [6]:
#range diyera
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [7]:
#create array with evenly spaced numbers within a specified range
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

# Two Dimensional array

In [8]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [10]:
a=np.array([[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]
          )

a[0,1]=20
a


array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [11]:
print("\n")
a[2:3]=1
a

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [12]:
a[0,2]=2
a[1,2]=2
a[2,2]=2
print (a)

[[ 1 20  2]
 [ 4  5  2]
 [ 1  1  2]]


In [13]:
#all elements 10 of 3*3 matrix
np.full((3, 3), 10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

# Randomly generated array

- NumPy can create arrays filled with random numbers
- To ensure the reporducibilitym you can set a seed using ```np.random. seed()```. It will generate the exact same random numbers for each executions.
- If you remove or change the seed values , the sequence fo random numbers will be changed.

In [14]:
np.random.rand(5)

array([0.12463601, 0.02045555, 0.9980053 , 0.38353717, 0.68473271])

In [15]:
np.random.seed(80)
np.random.rand(5)
#randomly numbers generated always comes between 0 and 1

array([0.52191572, 0.69940637, 0.26986897, 0.67448187, 0.90807208])

In [16]:
np.random.randn(5, 2)

array([[-1.03446493,  0.66424004],
       [-1.13937438, -0.89472205],
       [-0.2207972 , -0.43007258],
       [ 1.19972246,  0.1222967 ],
       [ 0.54794733, -0.52658091]])

In [17]:
np.random.randint(low=0, high=100,size=(5,2))

array([[ 7, 69],
       [96, 56],
       [15,  3],
       [94, 39],
       [51, 94]])